fav/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^alter/fav/$', views.FavAlterView.as_view(), name='fav-alter'),
]

test_app/urls.py
from django.conf.urls import url
from views import ArticleDetailView, ArticleListView

urlpatterns = [
    url(r'^article/list/(?P<pk>[0-9]+)/$', ArticleDetailView, name='article-detail'),
    url(r'^$', ArticleListView, name='article-list'),
]

fav/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import (
    GenericForeignKey)
from django.contrib.contenttypes.models import ContentType


class Favorite(models.Model):

    """ Represents an instance of Favorite """

    content_type = models.ForeignKey(ContentType, null=True)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, null=True, blank=True)
    cookie = models.CharField(null=True, max_length=256, blank=True)
    created = models.DateTimeField(auto_now_add=True)

test_app/models.py
from django.db import models
from fav.models import Favorite
from django.contrib.contenttypes.fields import GenericRelation


class Article(models.Model):
    title = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    favorites = GenericRelation(Favorite)

fav/forms.py
from django import forms
from . import models


class FavoriteForm(forms.ModelForm):

    class Meta:
        model = models.Favorite
        exclude = (
            'content_type', 'object_id', 'content_object', 'count')

fav/views.py
from .models import Favorite
from .forms import FavoriteForm
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse
from django.views.generic.edit import FormView
from django.middleware.csrf import get_token
from django.conf import settings 

class FavAlterView(FormView):

    """
    Enables authenticated users to Favorite/Unfavorite objects.
        getattr method sets default values for POSITIVE_NOTATION, 
    NEGATIVE_NOTATION, ALLOW_ANONYMOUS in the case they are not
    set in settings.py
    """

    form_class = FavoriteForm
    model = Favorite
    template_name = 'fav/fav_form.html'

    def form_valid(self, form):
        fav_value = self.request.POST['fav_value']
        csrf_token_value = get_token(self.request)
        if not self.request.session.exists(self.request.session.session_key):
            self.request.session.create()
        try:
            content_type = ContentType.objects.get(
                app_label=self.request.POST['app_name'],
                model=self.request.POST['model'].lower())
            model_object = content_type.get_object_for_this_type(
                id=self.request.POST['model_id'])
            if fav_value == getattr(settings, 'POSITIVE_NOTATION', 'Favorite'):
                fav = form.save(commit=False)
                fav.content_object = model_object
                if self.request.user.is_authenticated():
                    fav.save()
                else:
                    if getattr(settings, 'ALLOW_ANONYMOUS', 'TRUE') == "TRUE":
                        fav.cookie = self.request.session.session_key
                        fav.save()
                    else:
                        return JsonResponse({
                            'success': 0,
                            'error': "You have to sign in "})
                Favorite.objects.get(id=fav.id)
            else:
                if self.request.user.is_authenticated():
                    Favorite.objects.get(
                        object_id=model_object.id,
                        user=self.request.user,
                        content_type=content_type).delete()
                elif getattr(settings, 'ALLOW_ANONYMOUS', 'TRUE') == "TRUE":
                    Favorite.objects.get(
                        object_id=model_object.id,
                        cookie=self.request.session.session_key,
                        content_type=content_type).delete()
        except:
            return JsonResponse({
                'success': 0,
                'error': "You have to sign in "})
        return JsonResponse({"csrf": csrf_token_value})

    def form_invalid(self, form):
        return JsonResponse({
            'success': 0,
            'error': form.errors})

test_app/views.py
from models import Article
from django.views.generic import DetailView
from django.views.generic.list import ListView


class ArticleDetailView(DetailView):

    model = Article
    template_name = "test_app/article_detail.html"


class ArticleListView(ListView):

    model = Article
    template_name = "test_app/article_list.html"

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        return context

fav/templates/fav/fav_count.html
{% load favorite_tags %}
<div class = "fav_count_div{{target.id}}">{{fav_count}}</div>
    <input id= "fav_count{{target.id}}" value="{{fav_count}}" hidden>

fav/templates/fav/fav_form.html
{% load favorite_tags %}

	<form  method="" action="" class="fav-form{{target.id}}">     
		{% csrf_token %}
		{{ form.errors }}
		<br>
		{% if target %}	
			<input name="model" value="{% get_model_name target %}" hidden>
			<input name="model_id" value="{{ target.id }}" hidden>
			<input name="app_name" value="{% get_app_name target %}" hidden>
		{% endif %}
		{% if user.is_authenticated %}
		<input id="id_user" name="user" value="{% if user.is_authenticated %}{{ user.id }}{% endif %}" hidden>
		{% else %}
		<input id="id_cookie" name="cookie" value="{{cookie}}" hidden>
		{% endif %}
		<input  id="fav-button{{target.id}}" type="button" object="{{target.id}}" value="{{fav_value}}" class="fav-button"/>
	</form>
	<input name="positive_notation" value="{{positive_notation}}" hidden>
	<input name="negative_notation" value="{{negative_notation}}" hidden>
</body>
</html>

test_app/templates/test_app/article_detail.html
{% load favorite_tags %}
{% load static %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/fav.js' %}"></script>

<h2> Detailed view of test model </h2>
<h3> Title : {{object.title}} </h3> <br>
<h3> Description : {{object.description}} </h3>

{% if user.is_authenticated %}
Logged in user : {{user.username}} <br> 
{%  get_fav object user %}
{% else %}
{% get_fav_nouser object request.session.session_key %}
{% endif %}

{% get_fav_count object%}

test_app/templates/test_app/article_list.html
{% load favorite_tags %}
{% load static %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/fav.js' %}"></script>
<h1>Articles</h1>
<ul>
Logged in user : {{user.username}} <br> 
<br>
{% for object in object_list %}
<li>
Title : {{ object.title}} <br><br>
Description : {{ object.description }}

{% if user.is_authenticated %}
{%  get_fav object user %}
{% else %}
{% get_fav_nouser object request %}
{% endif %}
{% get_fav_count object%}<br><br>
 </li>
{% empty %}
<li>No articles yet.</li>
{% endfor %}
</ul>